#-----------------------------------------------------------------------------------
#
# An example script for running the Water in the Target neutrino beam "sub-simulation" in G4NuMI. -L.Loiacono
#

#
#I don't know what this does. But it was in the previous example macro.
#
/control/suppressAbortion 2

#
#Set the Debug Level for debugging messages.
#0 = debug off. Default is 0.
#
/NuMI/run/DebugLevel 0 

#
#Tell G4NuMI that you want to run the Neutrino beam simulation, default is false
#
/NuMI/run/useNuBeam true

#
#Tell G4NuMI that you want to run the simulation of water in the target. 
#This is a "sub-simulation" of the Neutrino beam simulation, default is false
#
/NuMI/run/useWaterInTgt ${do_target_water}

#Switch to the alternate horn1
#
/NuMI/det/Horn1IsAlternate ${do_horn1_new_geometry}

#Use refined definition of horn1
/NuMI/det/Horn1IsRefined ${do_horn1_fine_segmentation}

#
#Set the amount (length) of water that fills the target starting from the downstream end.
#Can't have less than 3 cm of water right now. 
#default and minimum is 3 cm
#
/NuMI/det/LengthOfWaterInTgt ${target_water_cm} cm

# The water layer around the inner conductor. Defaul value: 1 mm.
#
/NuMI/det/HornWaterLayerThickness ${horn_water_mm} mm

#
#Set the Run Period, default is -999 which is no run period at all. MUST SET IT.
#Run Period 0 is like a "default" run period, everything is aligned, it is not
#specific to any ACTUAL NuMI beam running period.
#
/NuMI/det/RunPeriod 0

#
#Use the Calibration corrected horn current value for the
#horn current configuration defined by BeamConfig (see next), default is true
#Note:This must be set BEFORE setting BeamConfig
#
/NuMI/det/UseCorrHornCurrent true

#
#Configure the neutirno beam. 
#This sets the TargetZ0 and Baffle Z0 and HornCurrent.
#Must be in the form \"LE#z#i\" or \"le#z#i\", where # is any number. 
#Examples are le010z185i, LE025.3z-200i, LE250z185.6i....etc.
#Note: cannot handle ME config right now.
#LE250z200i
/NuMI/det/BeamConfig ${beamconfig}

#Beam spot size
#Default is 1.4mm. For LE it should be 1.1mm (make it explicit in (ProcessG4NuMI.py)
/NuMI/Beam/SigmaX ${beam_spotsize_X} mm
/NuMI/Beam/SigmaY ${beam_spotsize_Y} mm

#Beam position shift
/NuMI/Beam/ShiftX ${beam_position_X} mm
/NuMI/Beam/ShiftY ${beam_position_Y} mm

#Magnetic field in decay pipe
#/NuMI/det/applyDecayPipeMagneticField false

#
#Use the Detailed Proton beam, true/false, default is false
#NOTE: Right now I don't know if the code for this and the parameter values are right.
#THIS NEEDS TO BE CHECKED!
#
#/NuMI/run/useDetailedProtonBeam true

#
#Kill tracking, true/false, default is true
#Set the energy at which to kill the particle
#default is 0.05 GeV. Note: This cut is specific for MINOS
#
#/NuMI/run/KillTracking true
#/NuMI/run/KillTrackingThreshold 0.05 GeV

#
#Use importance weighting, default is true
#
/NuMI/run/useNImpWeight true

#
#Add target position:
#
/NuMI/det/set/targetPosition ${target_position_X} ${target_position_Y} ${target_position_Z} cm
/NuMI/run/setMinervaPlaylist ${playlist}
#

# see NumiX meeting 08/2014 and minerva docdb 10512
/NuMI/det/set/horn1Position 0 0 3 cm
/NuMI/det/set/horn2Position 0 0 1000. cm

#Whether or not to create output ntuple with data_t
#default is false
#
/NuMI/output/outputNuNtuple true

#
#Directory and filename (with out the .root) to write output ntuple
#the RunID which gets set below gets appended to the filename
#
/NuMI/output/setNuNtupleFile ${outfile}

#
#Read in fluka hadrons file, true/false, default is false
#Set the fluka hadrons file path and name
#
#/NuMI/run/useFlukaInput true
#/NuMI/run/extNtupleFileName /minos/data/users/jyuko/fluka05root/fluka05_005.root

#
#If using external hadron file for input don't need to 
#and probably don't want to construct the target, default is true
#
#/NuMI/det/constructTarget false

# should we put some helium in the decay pipe?
# T=300K, P=0.9atm, rho=0.145*kg/m3 ... default is true
# /NuMI/det/heInDecayPipe false


#
#Update the geometry. ALWAYS do this HERE, never before this point. 
#The geometery is constructed BEFORE
#the macro is read. Need to reconstruct the geometry after reading in the macro.
#
/NuMI/det/update

#
# Allows the beginning seed to be set manually. This allows 
# rerunning simulations with the exact same initial conditions 
# to check for possible errors.
#
/NuMI/rndm/setRndmSeed ${seed}

#
# Allows the RunID, which is included in the
# output file name(s), to be set at runtime.
#
/NuMI/run/setRunID ${run}

#
# If NOT using an external hadron file then this establishes how 
# many particles(protons) to use during the simulation. To be consistent 
# with past neutrino ntuples each run uses 500000 protons
#
/run/beamOn ${pot}

#
#NOTE: To debug problems grep for "PROBLEM" in the output of the simulation
# "PROBLEM" statements are printed when there is a problem.
#
