/********************************************************************
* ./src/g4numiCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ./src/g4numiCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableg4numiCint();
extern void G__cpp_setup_inheritanceg4numiCint();
extern void G__cpp_setup_typetableg4numiCint();
extern void G__cpp_setup_memvarg4numiCint();
extern void G__cpp_setup_globalg4numiCint();
extern void G__cpp_setup_memfuncg4numiCint();
extern void G__cpp_setup_funcg4numiCint();
extern void G__set_cpp_environmentg4numiCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../include/data_t.hh"
#include "../include/hadmmtuple_t.hh"
#include "../include/draytupleSPB_t.hh"
#include "../include/Edep_t.hh"
#include "../include/draytupleMIB_t.hh"
#include "../include/absbkgtuple_t.hh"
#include "../include/zptuple_t.hh"
#include "../include/target_exit_t.hh"
#include "../include/ProdTuple_t.hh"
#include "../include/TrackInfo_t.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__g4numiCintLN_TClass;
extern G__linked_taginfo G__g4numiCintLN_TBuffer;
extern G__linked_taginfo G__g4numiCintLN_TMemberInspector;
extern G__linked_taginfo G__g4numiCintLN_string;
extern G__linked_taginfo G__g4numiCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__g4numiCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__g4numiCintLN_TString;
extern G__linked_taginfo G__g4numiCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__g4numiCintLN_data_t;
extern G__linked_taginfo G__g4numiCintLN_hadmmtuple_t;
extern G__linked_taginfo G__g4numiCintLN_draytupleSPB_t;
extern G__linked_taginfo G__g4numiCintLN_Edep_t;
extern G__linked_taginfo G__g4numiCintLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__g4numiCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__g4numiCintLN_draytupleMIB_t;
extern G__linked_taginfo G__g4numiCintLN_maplEintcOfloatcOlesslEintgRcOallocatorlEpairlEconstsPintcOfloatgRsPgRsPgR;
extern G__linked_taginfo G__g4numiCintLN_maplEintcOEdep_tcOlesslEintgRcOallocatorlEpairlEconstsPintcOEdep_tgRsPgRsPgR;
extern G__linked_taginfo G__g4numiCintLN_absbkgtuple_t;
extern G__linked_taginfo G__g4numiCintLN_zptuple_t;
extern G__linked_taginfo G__g4numiCintLN_target_exit_t;
extern G__linked_taginfo G__g4numiCintLN_ProdTuple_t;
extern G__linked_taginfo G__g4numiCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__g4numiCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__g4numiCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__g4numiCintLN_TVector3;
extern G__linked_taginfo G__g4numiCintLN_TLorentzVector;
extern G__linked_taginfo G__g4numiCintLN_TrackInfo_t;

/* STUB derived class for protected member access */
